version: '3'
services:
  myflaskwebservice:
    build: .
    ports:
      - 80:5000
    volumes:
      - .:/usr/src/app
    depends_on:
      - dbcontainer

  dbcontainer:
    image: mariadb
    volumes:
      - stravadata:/home/landon/Documents/mariadbtest
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: website
    ports:
      - 3306:3306

volumes:
  stravadata: